### ISSUE TITLE
Consider pulling google/woff2 as a submodule

### ISSUE THREAD

**Issue by rsheeter** [khaledhosny/ots#58] opened 2015-04-01 15:05 UTC
https://code.google.com/p/chromium/issues/detail?id=371267#c18 suggests we use google/woff2 as a submodule (as with brotli) rather than having a separate copy.

WDYT?

**Comment by behdad** [comment] 2015-04-01 17:46
I think that's a noble goal, for the sake of reducing number of implementations.

**Comment by khaledhosny** [comment] 2015-04-01 18:04
I agree on principle, but I’d hate to lose all WOFF 2 failure messages (there is quite a few of them), so I think we need a way to have the messages in google/woff2 and pass then down to ots.

**Comment by behdad** [comment] 2015-04-01 18:12
I think worst-case we can do a compile-time setting for the error messages, if not a runtime thing.

**Comment by irori** [comment] 2015-04-02 01:40
It would be great if you could upstream error reporting to google/woff2!

IMO, sanitisation error messages are important because the class of fonts that OTS accepts is undocumented and changes often as OTS evolves. On the other hand WOFF2 has a well defined spec, so decode error just indicates that there's a bug in the encoder or the decoder. It would be very useful for decoder / encoder authors, but less so for font authors / web developers.

So, a compile-time setting sounds like a reasonable option to me. (I'm not against having messages on browsers)

**Comment by khaledhosny** [comment] 2015-04-17 12:35
So in order to do this we need to:
- [ ] Make sure all spec conformance fixes in ots are merged back to google/woff2 decoder.
- [ ] Provide a mechanism for google/woff2 decoder to report failure messages, probably as a build time option.
- [ ] Drop the woff2 decoder from ots and pull in the google/woff2 one.

**Comment by rsheeter** [comment] 2015-04-17 15:11
I'm behind on woff2 pull requests :( Does https://github.com/google/woff2/pull/4 cover the first item or are there additional OTS-only fixes?

+1 for compile time switch for messages; I don't immediately see a compelling case for runtime.

**Comment by khaledhosny** [comment] 2015-04-17 15:21
I think there are few more fixes not included in google/woff2#4, I’ll add them to the pull request soon.

**Comment by khaledhosny** [comment] 2015-04-19 22:31
google/woff2#4 should now all the conformance changes that OTS had but was missing from google/woff2.

**Comment by behdad** [comment] 2015-04-21 00:01
Is there anything to be done about the fact that woff2 repo borrowed some code from OTS to begin with?

**Comment by rsheeter** [comment] 2015-04-22 15:50
Merged google/woff2#4.

**Comment by khaledhosny** [comment] 2015-06-13 13:13
After discussion with Rod, it seems that integrating the failure message with woff2 code in a way that OTS can utilize is not trivial, so I decided to just drop them for now. The code is in woff2 branch now and it seems to work, but I’m hitting google/woff2#15 now (OTS did not hit it before because it had google/woff2#18), especially with the some fonts in WOFF2 test suit, so I’m not sure if I should merge the branch now or wait until the issue is fixed?

**Closed** 2015-10-29 08:03 UTC
Labels: enhancement

**Comment by khaledhosny** [comment] 2015-10-29 16:32
This code has landed, any issues with the WOFF 2 implementation will need to be addressed in the google/woff2 repository.
