### ISSUE TITLE
-Wtautological-overlap-compare: warning triggered in cff_type2_charstring_test.cc

### ISSUE THREAD

**Issue by sylvestre** [khaledhosny/ots#194] opened 2019-08-14 14:49 UTC
Building Firefox with an [experimental warning](https://reviews.llvm.org/D66044) of clang triggers a new warning in an OTS test:

```
 4:33.99 /home/sylvestre/dev/mozilla/mozilla-central.hg/gfx/ots/tests/cff_type2_charstring_test.cc:80:21: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
 4:33.99   if (num <= -32768 && num >= 32767) {
 4:33.99       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
 4:33.99 /home/sylvestre/dev/mozilla/mozilla-central.hg/gfx/ots/tests/cff_type2_charstring_test.cc:81:24: error: code will never be executed [-Werror,-Wunreachable-code]
 4:33.99     const uint8_t v = (num % 0xff00u) >> 8;
 4:33.99                        ^~~
 4:33.99 /home/sylvestre/dev/mozilla/mozilla-central.hg/gfx/ots/tests/cff_type2_charstring_test.cc:80:14: note: silence by adding parentheses to mark code as explicitly dead
 4:33.99   if (num <= -32768 && num >= 32767) {
 4:33.99              ^
 4:33.99              /* DISABLES CODE */ ( )

```

**Comment by khaledhosny** [comment] 2019-08-14 14:55
Duplicate of #191

**Closed by khaledhosny** 2019-08-14 14:55 UTC

**Comment by sylvestre** [comment] 2019-08-14 15:00
Oups, thanks!
