### ISSUE TITLE
CFF fonts that use "put" in their charstrings fail OTS testing

### ISSUE THREAD

**Issue by Pomax** [khaledhosny/ots#84] opened 2015-11-16 21:16 UTC
I have a simple test font that passes OTS testing:

```
data:font/opentype;base64,T1RUTwAKAIAAAwAgQ0ZGIOQb724AAAQEAAABsEdTVUIgpSV2AAAFtAAAAGJPUy8yMNskngAAARAAAABgY21hcAGPAlsAAAN4AAAAamhlYWRh5ENVAAAArAAAADZoaGVhBngBOgAAAOQAAAAkaG10eAKoABQAAAYYAAAAIG1heHAACFAAAAABCAAAAAZuYW1lAa1a/wAAAXAAAAIHcG9zdAADAAEAAAPkAAAAIAABAAAAAQAAV7chel8PPPUAAAQAAAAAAAAAAAAAAAAAAAAAAAAU/84CvAKKAAAACAACAAAAAAAAAAEAAAPO/ooAAAKoAAAAAAKoAAAAAAAAAAAAAAAAAAAAAAAIAABQAAAIAAAAAwAAAZAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAID0pIABAAGMAfgKK/84BRAPOAXYAAAABAAAAAAAAAAAAAAB+AAYAAAAUAPYAAQAAAAAAAAAMAAAAAQAAAAAAAQAGACQAAQAAAAAAAgAHADYAAQAAAAAAAwABAEsAAQAAAAAABAARAE4AAQAAAAAABQALAIEAAQAAAAAABgAKAKIAAQAAAAAABwAOAMAAAQAAAAAADQAMAOoAAQAAAAAAEwABAQ4AAwABBAkAAAAYAAwAAwABBAkAAQAMACoAAwABBAkAAgAOAD0AAwABBAkAAwACAEwAAwABBAkABAAiAF8AAwABBAkABQAWAIwAAwABBAkABgAUAKwAAwABBAkABwAcAM4AAwABBAkADQAYAPYAAwABBAkAEwACAQ9MaWNlbnNlLWZyZWUATABpAGMAZQBuAHMAZQAtAGYAcgBlAGVDdXN0b20AQwB1AHMAdABvAG1SZWd1bGFyAFIAZQBnAHUAbABhAHItAC1DdXN0b20gR2x5cGggRm9udABDAHUAcwB0AG8AbQAgAEcAbAB5AHAAaAAgAEYAbwBuAHRWZXJzaW9uIDEuMABWAGUAcgBzAGkAbwBuACAAMQAuADBjdXN0b21mb250AGMAdQBzAHQAbwBtAGYAbwBuAHRUcmFkZW1hcmstZnJlZQBUAHIAYQBkAGUAbQBhAHIAawAtAGYAcgBlAGVMaWNlbnNlLWZyZWUATABpAGMAZQBuAHMAZQAtAGYAcgBlAGV+AH4AAAAAAQADAAEAAAAMAAQAXgAAABAAEAADAAAAYwBtAG8AcwB0AHUAfv//AAAAYwBtAG8AcwB0AHUAfv///57/lf+U/5H/kf+R/4kAAQAAAAAAAAAAAAAAAAAAAAAAAQACAAMABAAFAAYABwAAAAMAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAQBAAEBAQtjdXN0b21mb250AAEBASP4GwD4HAL4HQP4GQSMDZ9Z+VD5HgX35Q/39BD3/RGb+DQSAAoBAQwdIyQlJicoKSpWZXJzaW9uIDEuMEN1c3RvbSBHbHlwaCBGb250Q3VzdG9tY21vc3R1fgADAQE9R9oMG4sMFP8AAwWHDBuMDBSPjQwU/wAxAVyODBQMHAwLiwwVDBiNDBUMGI8MFI4MFY8MFQwLDAyNDBUMGAv/AAEAOQwKIB0LjwwUjgwUjQwUjAwUiwwUiwwVIB2QDBSLDBUhHZEMFI4MFYwMFQwLkgwUjwwVjQwVDAuTDBSSDBWRDBUMGJQMFJMMFZEMFQwYlQwUjgwVlAwVlQwVDA4MCgwKlgwUkgwVkQwVDBiXDBSTDBWQDBUMGJgMFI0MFZcMFZgMFQwKDAqZDBQMFYsMFYwMFY0MFZgMFZkLAAGKAYsBjAGNAY4BjwGQAAcBAgMEBQYHAAgBAQIDBAUGBwgsDg4ODg4ODp9ZFYv5UAX5PIsFi/1QBf08iwX3Pu8V+BCLBYv4JAX8EIsFDouLBouLCJUKlQv5UBT5UBUAAQAAAAoAJAAyAAJERkxUAA5sYXRuAA4ABAAAAAD//wABAAAAAWxpZ2EACAAAAAEAAAABAAQABAAAAAEACAABAAgAAQASAAIAAQABAAEAAAABAAQABwAGAAYABAAFAAMAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKoABQ=
```

This font has a charstring for the character `~` that is really simple:

```
  20  -50 rmoveto
   0  700 rlineto
 680    0 rlineto
   0 -700 rlineto
-680    0 rlineto
 170  100 rmoveto
 380    0 rlineto
   0  400 rlineto
-380    0 rlineto
endchar
```

If I prepend that charstring with `random drop` (which injects a random 16.16 decimal value between 0 and 1, and then immediately drops it off the stack again) then Adobe's FDK tool `tx` says this charstring is perfectly fine, recognizing that the "random" + "drop" combination is a noop, but OTS now fails the font, claiming it can't parse the charstring.

Font code:

```
data:font/opentype;base64,T1RUTwAKAIAAAwAgQ0ZGIPgy+4AAAAQEAAABtEdTVUIgpSV2AAAFuAAAAGJPUy8yMNskngAAARAAAABgY21hcAGPAlsAAAN4AAAAamhlYWRh5ENVAAAArAAAADZoaGVhBngBOgAAAOQAAAAkaG10eAKoABQAAAYcAAAAIG1heHAACFAAAAABCAAAAAZuYW1lAa1a/wAAAXAAAAIHcG9zdAADAAEAAAPkAAAAIAABAAAAAQAAL4kJSl8PPPUAAAQAAAAAAAAAAAAAAAAAAAAAAAAU/84CvAKKAAAACAACAAAAAAAAAAEAAAPO/ooAAAKoAAAAAAKoAAAAAAAAAAAAAAAAAAAAAAAIAABQAAAIAAAAAwAAAZAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAID0pIABAAGMAfgKK/84BRAPOAXYAAAABAAAAAAAAAAAAAAB+AAYAAAAUAPYAAQAAAAAAAAAMAAAAAQAAAAAAAQAGACQAAQAAAAAAAgAHADYAAQAAAAAAAwABAEsAAQAAAAAABAARAE4AAQAAAAAABQALAIEAAQAAAAAABgAKAKIAAQAAAAAABwAOAMAAAQAAAAAADQAMAOoAAQAAAAAAEwABAQ4AAwABBAkAAAAYAAwAAwABBAkAAQAMACoAAwABBAkAAgAOAD0AAwABBAkAAwACAEwAAwABBAkABAAiAF8AAwABBAkABQAWAIwAAwABBAkABgAUAKwAAwABBAkABwAcAM4AAwABBAkADQAYAPYAAwABBAkAEwACAQ9MaWNlbnNlLWZyZWUATABpAGMAZQBuAHMAZQAtAGYAcgBlAGVDdXN0b20AQwB1AHMAdABvAG1SZWd1bGFyAFIAZQBnAHUAbABhAHItAC1DdXN0b20gR2x5cGggRm9udABDAHUAcwB0AG8AbQAgAEcAbAB5AHAAaAAgAEYAbwBuAHRWZXJzaW9uIDEuMABWAGUAcgBzAGkAbwBuACAAMQAuADBjdXN0b21mb250AGMAdQBzAHQAbwBtAGYAbwBuAHRUcmFkZW1hcmstZnJlZQBUAHIAYQBkAGUAbQBhAHIAawAtAGYAcgBlAGVMaWNlbnNlLWZyZWUATABpAGMAZQBuAHMAZQAtAGYAcgBlAGV+AH4AAAAAAQADAAEAAAAMAAQAXgAAABAAEAADAAAAYwBtAG8AcwB0AHUAfv//AAAAYwBtAG8AcwB0AHUAfv///57/lf+U/5H/kf+R/4kAAQAAAAAAAAAAAAAAAAAAAAAAAQACAAMABAAFAAYABwAAAAMAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAQBAAEBAQtjdXN0b21mb250AAEBASP4GwD4HAL4HQP4GQSMDZ9Z+VD5HgX35Q/39BD3/RGb+DgSAAoBAQwdIyQlJicoKSpWZXJzaW9uIDEuMEN1c3RvbSBHbHlwaCBGb250Q3VzdG9tY21vc3R1fgADAQE9R9oMG4sMFP8AAwWHDBuMDBSPjQwU/wAxAVyODBQMHAwLiwwVDBiNDBUMGI8MFI4MFY8MFQwLDAyNDBUMGAv/AAEAOQwKIB0LjwwUjgwUjQwUjAwUiwwUiwwVIB2QDBSLDBUhHZEMFI4MFYwMFQwLkgwUjwwVjQwVDAuTDBSSDBWRDBUMGJQMFJMMFZEMFQwYlQwUjgwVlAwVlQwVDA4MCgwKlgwUkgwVkQwVDBiXDBSTDBWQDBUMGJgMFI0MFZcMFZgMFQwKDAqZDBQMFYsMFYwMFY0MFZgMFZkLAAGKAYsBjAGNAY4BjwGQAAcBAgMEBQYHAAgBAQIDBAUGBwgwDg4ODg4ODgwXDBKfWRWL+VAF+TyLBYv9UAX9PIsF9z7vFfgQiwWL+CQF/BCLBQ6LiwaLiwiVCpUL+VAU+VAVAAEAAAAKACQAMgACREZMVAAObGF0bgAOAAQAAAAA//8AAQAAAAFsaWdhAAgAAAABAAAAAQAEAAQAAAABAAgAAQAIAAEAEgACAAEAAQABAAAAAQAEAAcABgAGAAQABQADAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqAAU
```

It looks very much like OTS doesn't recognise the `random` instruction - to confirm, I tried `100 drop` instead, and OTS has no issues with the font, so it's not the act of pushing a value onto the stack and then dropping it.

**Comment by anthrotype** [comment] 2015-11-16 21:19
Duplicate of #83?

**Comment by Pomax** [comment] 2015-11-16 21:20
different operator.

**Comment by anthrotype** [comment] 2015-11-16 21:20
Sorry :)

**Comment by HinTak** [comment] 2016-08-15 21:37
It might be a good approach to offload the work to an enhanced version of Adobe's parser, along the line I suggested in:
https://github.com/khaledhosny/ots/issues/97

**Comment by khaledhosny** [comment] 2019-02-14 00:33
I don’t think I’m ever going to do this, but patches are always welcomed.

**Closed by khaledhosny** 2019-02-14 00:33 UTC
Labels: enhancement
